default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dbuser
  password: dbpass
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: oppw4-character-randomizer_development

test:
  <<: *default
  database: oppw4-character-randomizer_test

production:
  <<: *default
  database: oppw4-character-randomizer_production
  username: oppw4-character-randomizer
  password: <%= ENV['OPPW4-CHARACTER-RANDOMIZER_DATABASE_PASSWORD'] %>
