CharacterCategory.create(name: '麦わらの一味', image: 'straw_hats.png')
CharacterCategory.create(name: '四皇', image: 'four_emperors.png')
CharacterCategory.create(name: '王下七武海', image: 'seven_warloads.png')
CharacterCategory.create(name: '最悪の世代', image: 'worst_generations.png')
CharacterCategory.create(name: '海軍・世界政府', image: 'marines.png')
CharacterCategory.create(name: '革命軍', image: 'revolutionary_army.png')
CharacterCategory.create(name: 'ジェルマ66', image: 'germa_66s.png')
CharacterCategory.create(name: 'ワノ国', image: 'wano_country.png')
CharacterCategory.create(name: 'その他', image: 'others.png')

ActionType.create(name: 'パワータイプ', image: 'power_types.png')
ActionType.create(name: 'スピードタイプ', image: 'speed_types.png')
ActionType.create(name: 'テクニックタイプ', image: 'technique_types.png')
ActionType.create(name: 'スカイタイプ', image: 'sky_types.png')

Character.create(name: 'ルフィ', image: 'luffy.png', character_category_id: 1, action_type_id: 1)
Character.create(name: 'ルフィ（新世界）', image: 'luffy_new_world.png', character_category_id: 1, action_type_id: 1)
Character.create(name: 'ゾロ', image: 'zoro.png', character_category_id: 1, action_type_id: 1)
Character.create(name: 'ゾロ（新世界）', image: 'zoro_new_world.png', character_category_id: 1, action_type_id: 1)
Character.create(name: 'ナミ（新世界）', image: 'nami_new_world.png', character_category_id: 1, action_type_id: 3)
Character.create(name: 'ウソップ', image: 'usopp.png', character_category_id: 1, action_type_id: 3)
Character.create(name: 'ウソップ（新世界）', image: 'usopp_new_world.png', character_category_id: 1, action_type_id: 3)
Character.create(name: 'サンジ', image: 'sanji.png', character_category_id: 1, action_type_id: 2)
Character.create(name: 'サンジ（新世界）', image: 'sanji_new_world.png', character_category_id: 1, action_type_id: 4)
Character.create(name: 'チョッパー（新世界）', image: 'chopper_new_world.png', character_category_id: 1, action_type_id: 3)
Character.create(name: 'ロビン（新世界）', image: 'robin_new_world.png', character_category_id: 1, action_type_id: 3)
Character.create(name: 'フランキー（新世界）', image: 'franky_new_world.png', character_category_id: 1, action_type_id: 1)
Character.create(name: 'ブルック（新世界）', image: 'brook_new_world.png', character_category_id: 1, action_type_id: 2)
Character.create(name: 'ジンベエ（新世界）', image: 'jinbe_new_world.png', character_category_id: 1, action_type_id: 1)
Character.create(name: '白ひげ', image: 'whitebeard.png', character_category_id: 2, action_type_id: 1)
Character.create(name: 'マルコ', image: 'marco.png', character_category_id: 2, action_type_id: 4)
Character.create(name: 'エース', image: 'ace.png', character_category_id: 2, action_type_id: 2)
Character.create(name: 'カイドウ', image: 'kaido.png', character_category_id: 2, action_type_id: 1)
Character.create(name: 'ビッグ・マム', image: 'big_mom.png', character_category_id: 2, action_type_id: 1)
Character.create(name: 'カタクリ', image: 'katakuri.png', character_category_id: 2, action_type_id: 2)
Character.create(name: 'スムージー', image: 'smoothie.png', character_category_id: 2, action_type_id: 1)
Character.create(name: 'クラッカー', image: 'cracker.png', character_category_id: 2, action_type_id: 2)
Character.create(name: 'シャンクス', image: 'shanks.png', character_category_id: 2, action_type_id: 1)
Character.create(name: '黒ひげ', image: 'blackbeard.png', character_category_id: 2, action_type_id: 1)
Character.create(name: 'ミホーク', image: 'mihawk.png', character_category_id: 3, action_type_id: 1)
Character.create(name: 'ドフラミンゴ', image: 'doflamingo.png', character_category_id: 3, action_type_id: 4)
Character.create(name: 'クロコダイル', image: 'crocodile.png', character_category_id: 3, action_type_id: 4)
Character.create(name: 'ハンコック', image: 'hancock.png', character_category_id: 3, action_type_id: 3)
Character.create(name: 'バギー', image: 'buggy.png', character_category_id: 3, action_type_id: 3)
Character.create(name: 'ロー', image: 'law.png', character_category_id: 4, action_type_id: 3)
Character.create(name: 'キッド', image: 'kid.png', character_category_id: 4, action_type_id: 1)
Character.create(name: 'キラー', image: 'killer.png', character_category_id: 4, action_type_id: 2)
Character.create(name: 'ホーキンス', image: 'hawkins.png', character_category_id: 4, action_type_id: 3)
Character.create(name: 'ベッジ', image: 'bege.png', character_category_id: 4, action_type_id: 3)
Character.create(name: 'ドレーク', image: 'drake.png', character_category_id: 4, action_type_id: 1)
Character.create(name: 'ウルージ', image: 'urouge.png', character_category_id: 4, action_type_id: 1)
Character.create(name: '赤犬', image: 'akainu.png', character_category_id: 5, action_type_id: 1)
Character.create(name: '黄猿', image: 'kizaru.png', character_category_id: 5, action_type_id: 4)
Character.create(name: '青雉', image: 'aokiji.png', character_category_id: 5, action_type_id: 3)
Character.create(name: '藤虎', image: 'fujitora.png', character_category_id: 5, action_type_id: 1)
Character.create(name: 'スモーカー', image: 'smoker.png', character_category_id: 5, action_type_id: 4)
Character.create(name: 'たしぎ', image: 'tashigi.png', character_category_id: 5, action_type_id: 2)
Character.create(name: 'ルッチ', image: 'lucci.png', character_category_id: 5, action_type_id: 4)
Character.create(name: 'サボ', image: 'sabo.png', character_category_id: 6, action_type_id: 2)
Character.create(name: 'イワンコフ', image: 'ivankov.png', character_category_id: 6, action_type_id: 3)
Character.create(name: 'ジャッジ', image: 'judge.png', character_category_id: 7, action_type_id: 4)
Character.create(name: 'レイジュ', image: 'reiju.png', character_category_id: 7, action_type_id: 4)
Character.create(name: 'イチジ', image: 'ichiji.png', character_category_id: 7, action_type_id: 4)
Character.create(name: 'ニジ', image: 'niji.png', character_category_id: 7, action_type_id: 4)
Character.create(name: 'ヨンジ', image: 'yonji.png', character_category_id: 7, action_type_id: 4)
Character.create(name: 'おでん', image: 'oden.png', character_category_id: 8, action_type_id: 1)
Character.create(name: '錦えもん', image: 'kinemon.png', character_category_id: 8, action_type_id: 3)
Character.create(name: 'お菊', image: 'okiku.png', character_category_id: 8, action_type_id: 2)
Character.create(name: 'バルトロメオ', image: 'bartolomeo.png', character_category_id: 9, action_type_id: 3)
Character.create(name: 'キャベンディッシュ', image: 'cavendish.png', character_category_id: 9, action_type_id: 2)
Character.create(name: 'キャロット', image: 'carrot.png', character_category_id: 9, action_type_id: 2)

Rank.create(name: '"東の海"級', image: 'east_blue.png')
Rank.create(name: '"偉大なる航路"級', image: 'grand_line.png')
Rank.create(name: '"新世界"級', image: 'new_world.png')

Stage.create(name: 'アルバーナ', image: 'alubarna.png')
Stage.create(name: 'エニエス・ロビー', image: 'enies_lobby.png')
Stage.create(name: 'マリンフォード', image: 'marineford.png')
Stage.create(name: '海軍本部', image: 'marine_headquarters.png')
Stage.create(name: 'ドレスローザ', image: 'dressrosa.png')
Stage.create(name: 'ホールケーキアイランド', image: 'whole_cake_island.png')
Stage.create(name: '鏡世界', image: 'mirror_world.png')
Stage.create(name: '鬼ヶ島', image: 'onigashima.png')

User.create(name: 'Sylpha', email: 'sylpha.games@gmail.com', password: 'password')
